name: deploy-comments

on:
  push:
    branches:
      - main
    paths:
      - 'comments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd comments && docker build -t fdegmecic/comments .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push fdegmecic/comments
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save fipubook
      - run: kubectl rollout restart deployment comments-depl